name: Go Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - doublyLinkedList
          - queue
          - stack
          - unionfind
          - binarysearchtree
          # - dArray QSORT is failing
          # Add more packages as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1 # Replace with your desired Go version

      - name: Run Tests
        run: go test -cover ./$package/...
        env:
          package: ${{ matrix.package }}
